Repository SV-Winter-BootCamp-Team-C/frontend, pull requests merged in 2024-01, with the labels that each got.

#4 chore: 프론트 초기 세팅 완료
  .eslintrc.cjs
  .gitignore
  .husky/pre-commit
  .prettierrc
  README.md
  index.html
  package-lock.json
  package.json
  public/vite.svg
  src/App.css
  src/App.tsx
  src/GlobalStyle.tsx
  src/Router.tsx
  src/assets/react.svg
  src/index.css
  src/main.tsx
  src/vite-env.d.ts
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
Labels: 환경설정

#6 chore: Dockerfile 세팅
  Dockerfile
Labels: 환경설정

#8 Chore#7 Tailwind, React-Query 초기세팅
  .eslintrc.cjs
  .prettierrc
  package-lock.json
  package.json
  postcss.config.js
  src/App.tsx
  src/GlobalStyle.tsx
  src/index.css
  src/main.tsx
  src/queryClient.ts
  tailwind.config.js
Labels: 환경설정

#10 design: tailwind config 파일 작성
  .prettierrc
  src/global.css
  src/index.css
  src/main.tsx
  tailwind.config.js
Labels: 환경설정

#14 design: 알림창, navbar 퍼블리싱
  .eslintrc.cjs
  src/App.css
  src/Router.tsx
  src/assets/closebtn.svg
  src/assets/logout.svg
  src/assets/navAll.svg
  src/assets/navAnalysis.svg
  src/assets/navForm.svg
  src/assets/navRes.svg
  src/assets/profile.svg
  src/components/common/Alert.tsx
  src/components/common/Navbar.tsx
  src/global.css
  src/pages/Home.tsx
  tailwind.config.js
Labels: UI디자인

#18 design: 스타트 페이지 퍼블리싱
  .eslintrc.cjs
  src/Router.tsx
  src/assets/arrowRight.svg
  src/assets/flexLine.svg
  src/assets/graph1.svg
  src/assets/graph2.svg
  src/assets/iconStart.svg
  src/assets/newIdea.png
  src/assets/plus.svg
  src/assets/rectangle.svg
  src/assets/star1.svg
  src/assets/star2.svg
  src/assets/star3.svg
  src/assets/star4.svg
  src/assets/star5.svg
  src/assets/teamWork.png
  src/pages/Start.tsx
Labels: UI디자인

#21 design: 객관식 퍼블리싱
  src/assets/add.svg
  src/assets/copy.svg
  src/assets/delete.svg
  src/assets/imageadd.svg
  src/assets/trashcan.svg
  src/assets/type.svg
  src/components/common/surveytype/Multiplechoice.tsx
Labels: UI디자인

#23 Design#15 설문 조회 페이지 퍼블리싱
  .eslintrc.cjs
  package-lock.json
  package.json
  src/Router.tsx
  src/assets/menuAnalysis.svg
  src/assets/menuDel.svg
  src/assets/menuEdit.svg
  src/assets/menuLink.svg
  src/assets/menuSee.svg
  src/assets/open.svg
  src/assets/participants.svg
  src/assets/private.svg
  src/assets/search.svg
  src/assets/surveyDefault.png
  src/components/common/Alert.tsx
  src/components/common/Button.tsx
  src/components/common/Navbar.tsx
  src/components/survey/SurveyCover.tsx
  src/components/survey/SurveyCoverMenu.tsx
  src/components/survey/SurveyForm.tsx
  src/global.css
  src/layout/MainLayout.tsx
  src/pages/AllForm.tsx
  src/pages/Home.tsx
  src/pages/MyForm.tsx
  src/pages/MyResponse.tsx
  src/types/survey.ts
  src/utils/calculateRemainingDays.ts
Labels: UI디자인

#25 bug: navbar 색상 수정
  src/Router.tsx
  src/assets/navAnalysis.svg
  src/components/common/Navbar.tsx
  src/components/survey/SurveyCover.tsx
  src/components/survey/SurveyCoverMenu.tsx
  src/components/survey/SurveyForm.tsx
  src/global.css
Labels: 오류수정

#29 design:설문지 스타일 선택 페이지 퍼블리싱
  package-lock.json
  package.json
  src/Router.tsx
  src/assets/calender.svg
  src/assets/deleteIcon.svg
  src/assets/insertImage.svg
  src/assets/privateIcon.svg
  src/assets/publicIcon.svg
  src/components/common/Alert.tsx
  src/pages/Createstyle.tsx
  src/pages/Start.tsx
  tailwind.config.js
Labels: UI디자인

#31 fix: package.json 수정
  package.json
Labels: 오류수정

#36 Fix:react-custom-scrollbars-2로 교체
  package-lock.json
  package.json
  src/pages/Createstyle.tsx
Labels: 오류수정

#38 Feat:ResponseForm ScrollBar add
  src/pages/ResponseForm.tsx
Labels: UI디자인

#39 feat: transition 적용
  package-lock.json
  package.json
  src/components/common/Alert.tsx
  src/components/common/Button.tsx
  src/components/survey/SurveyForm.tsx
  src/global.css
  src/layout/MainLayout.tsx
  src/pages/AllForm.tsx
  src/pages/Login.tsx
  src/pages/MyForm.tsx
  src/pages/Signup.tsx
  src/pages/Start.tsx
Labels: 오류수정

#43 Feat:surveyResult SubjectQuestoin/Qusetion ScrollBar add
  src/components/surveyResult/Question/Question.tsx
  src/components/surveyResult/Question/SubjectQuestion.tsx
  src/pages/ResultPage.tsx
Labels: UI디자인

#45 design: 설문 문항 생성 페이지
  package-lock.json
  package.json
  src/Router.tsx
  src/assets/createCheck.svg
  src/assets/createDrop.svg
  src/assets/createMultiple.svg
  src/assets/createSubjective.svg
  src/components/createSurvey/CreateQuestion.tsx
  src/components/createSurvey/CreateQuestionMenu.tsx
  src/components/survey/SurveyCoverMenu.tsx
  src/pages/AllForm.tsx
  src/pages/Create.tsx
  src/pages/Createstyle.tsx
  src/pages/MyForm.tsx
Labels: UI디자인

#47 fix: 버튼 위치 수정
  src/Router.tsx
  src/components/common/Button.tsx
  src/components/surveyResult/Response/Response.tsx
Labels: 오류수정

#51 Design:MyProfile Modal Window 띄우기
  src/assets/pencil.svg
  src/components/common/MyProfileModal.tsx
  src/components/common/Navbar.tsx
Labels: UI디자인, 기능구현

#54 chore: react-query 전역 에러 핸들링 코드 추가
  .eslintrc.cjs
  src/App.tsx
  src/queryClient.ts
Labels: 환경설정

#56 chore: zustand 세팅 및 설정 완료
  package-lock.json
  package.json
  src/components/common/Navbar.tsx
  src/pages/Login.tsx
  src/store/AuthStore.tsx
  src/store/NavbarStore.tsx
Labels: 환경설정

#57 design: 로딩중 컴포넌트
  src/App.tsx
  src/Router.tsx
  src/components/common/Loading.tsx
  src/components/common/MyProfileModal.tsx
  src/layout/MainLayout.tsx
Labels: UI디자인

#58 fix: type 값 수정
  src/components/responsetype/ResponseCheckBox.tsx
  src/components/responsetype/ResponseDropDown.tsx
  src/components/responsetype/ResponseMultipleChoice.tsx
  src/components/responsetype/ResponseSubjective.tsx
  src/components/staticresponse/StaticCheckBox.tsx
  src/components/staticresponse/StaticDropDown.tsx
  src/components/staticresponse/StaticMultipleChoice.tsx
  src/components/staticresponse/StaticSubjective.tsx
  src/components/survey/SurveyForm.tsx
  src/components/surveyResult/Question/PieChart.tsx
  src/components/surveyResult/Question/Question.tsx
  src/components/surveyResult/Question/SubjectQuestion.tsx
  src/pages/MyAnswer.tsx
  src/pages/ResponseForm.tsx
  src/queryClient.ts
  src/types/questionData.ts
  src/types/survey.ts
Labels: 오류수정

#63 feat: 로그인, 회원가입 기능 구현
  src/api/login.ts
  src/api/signup.ts
  src/assets/alertError.svg
  src/assets/alertSuccess.svg
  src/components/common/Alert.tsx
  src/pages/Login.tsx
  src/pages/Signup.tsx
  src/queryClient.ts
  src/store/AuthStore.tsx
  src/types/apiResponseError.ts
  src/types/auth.ts
Labels: 기능구현

#66 feat: 회원가입시 이메일 중복 확인 기능 추가
  src/api/signup.ts
  src/pages/Login.tsx
  src/pages/Signup.tsx
Labels: UI디자인, 기능구현

#69 feat: 설문 조회 API 연동
  src/api/getForm.ts
  src/assets/noImage.png
  src/assets/surveyDefault.png
  src/components/survey/SurveyCover.tsx
  src/components/survey/SurveyForm.tsx
  src/hooks/usePaginationSurveyList.ts
  src/pages/AllForm.tsx
  src/pages/MyForm.tsx
  src/pages/MyResponse.tsx
  src/queryClient.ts
  src/types/survey.ts
Labels: 기능구현

#68 Feat: 설문지 스타일/문항생성페이지 기능구현
  src/api/myprofile.ts
  src/components/common/MyProfileModal.tsx
  src/components/common/Navbar.tsx
Labels: 기능구현

#73 feat: 설문 결과 페이지 API 연동 완료
  src/api/getResult.ts
  src/components/common/Alert.tsx
  src/components/common/Button.tsx
  src/components/common/Loading.tsx
  src/components/survey/SurveyCover.tsx
  src/components/survey/SurveyCoverMenu.tsx
  src/components/survey/SurveyForm.tsx
  src/components/surveyResult/Question/PieChart.tsx
  src/components/surveyResult/Question/Question.tsx
  src/components/surveyResult/Question/SubjectQuestion.tsx
  src/components/surveyResult/Response/Response.tsx
  src/pages/ResultPage.tsx
  src/types/answerData.ts
  src/types/questionData.ts
  src/types/survey.ts
Labels: 기능구현

#75 fix: 설문 결과 분석 경로 수정
  src/Router.tsx
  src/components/survey/SurveyForm.tsx
Labels: 오류수정

#79 feat: 설문 url 공유 기능
  src/api/surveyMenu.ts
  src/components/common/Loading.tsx
  src/components/common/ShareMailModal.tsx
  src/components/survey/SurveyCoverMenu.tsx
Labels: 기능구현

#82 feat: 비밀번호 변경, 로그아웃 기능
  src/api/myprofile.ts
  src/components/common/MyProfileModal.tsx
  src/components/common/Navbar.tsx
  src/store/AuthStore.tsx
Labels: 기능구현

#86 feat:All 페이지 검색 기능
  src/api/getForm.ts
  src/components/survey/SurveyForm.tsx
  src/hooks/usePaginationSurveyList.ts
  src/pages/AllForm.tsx
  src/pages/MyResponse.tsx
  src/types/questionData.ts
  src/types/survey.ts
Labels: 기능구현

#88 feat: 설문 생성 API 수정
  Dockerfile
  src/api/getForm.ts
  src/api/survey.ts
  src/components/createSurvey/CreateQuestion.tsx
  src/components/createSurvey/CreateQuestionMenu.tsx
  src/components/responsetype/ResponseCheckBox.tsx
  src/components/responsetype/ResponseMultipleChoice.tsx
  src/components/staticresponse/StaticCheckBox.tsx
  src/components/staticresponse/StaticMultipleChoice.tsx
  src/pages/Create.tsx
  src/pages/ResponseForm.tsx
  src/store/AuthStore.tsx
  src/types/create.ts
  src/types/editableSurvey.ts
  src/types/survey.ts
  src/utils/getRoundedClass.ts
Labels: 오류수정, 기능구현

#89 feat:이미지 검색 기능 구현
  src/api/imageSearch.ts
  src/components/common/ImageSearchModal.tsx
  src/pages/Create.tsx
Labels: 기능구현

#91 bug:이미지 검색 충돌 수정
  src/pages/Create.tsx
Labels: 오류수정
